### ISSUE TITLE
How do you actually run the code?

### ISSUE THREAD

**Issue by ysiahpoosh** [alexbw/Netflix-Prize#2]
I'm new to machine learning and wanted to see an example of a recommendation system running, but I am not sure how to actually run your code. Thanks for putting this up online, and thanks for the help!

**Comment by alexbw** [comment]
Oof it's probably been ten years since I've worked on this codebase -- to
learn ML, you're much better off taking a Coursera or edX course than
sifting through my old code. In any case, I unfortunately don't have the
bandwidth to see how to start up this code again.
